Always load bashrc

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,45 +1,52 @@
 #!/usr/bin/env bash
-[ ! "$HOME" ] && { echo "Missing \$HOME env variable"; exit 1; }
 cd "$(dirname "$0")" || { echo "Can't chdir into $(dirname "$0")"; exit 1; }
+[ ! -d "$(echo ~)" ] || { echo "Missing HOME dir: " ~; exit 1; }
 
 # Create backup dir
-rm -Rf "$HOME/.dotfiles_backup"
-mkdir -p "$HOME/.dotfiles_backup"
+rm -Rf ~/.dotfiles_backup
+mkdir -p ~/.dotfiles_backup
 
 # Install ~/.ssh/config on Darwin
 if [ "$(uname)" == "Darwin" ]; then
-  echo -n "$HOME/.ssh/config - copying..."
-  [ -f "$HOME/.ssh/config" ] && mv -f "$HOME/.ssh/config" "$HOME/.dotfiles_backup" && echo " [saved backup]" || echo
-  mkdir -p "$HOME/.ssh/control"
-  cp -f "$HOME/.dotfiles/ssh_config_darwin" "$HOME/.ssh/config"
+  echo -n "$(echo ~)/.ssh/config - copying..."
+  [ -f ~/.ssh/config ] && mv -f ~/.ssh/config ~/.dotfiles_backup && echo " [saved backup]" || echo
+  mkdir -p ~/.ssh/control
+  cp -f ~/.dotfiles/ssh_config_darwin ~/.ssh/config
 fi
 
 safe_copy() {
-  echo -n "$HOME/.$1 - copying..." 
-  [ -f "$HOME/.$1" ] && mv -f "$HOME/.$1" "$HOME/.dotfiles_backup" && echo " [saved backup]" || echo
-  cp -f "$HOME/.dotfiles/$1" "$HOME/.$1"
+  echo -n "$(echo ~)/.$1 - copying..."
+  [ -f ~/.$1 ] && mv -f ~/.$1 ~/.dotfiles_backup && echo " [saved backup]" || echo
+  cp -f ~/.dotfiles/$1 ~/.$1
 }
 
-# Install dotfiles on $HOME
-DOTFILES_SAFE=( bashrc bash_common gitconfig gitignore_global 
+# Install dotfiles on ~
+DOTFILES_SAFE=( bashrc bash_common bash_aliases gitconfig gitignore_global
                 vimrc inputrc tmux.conf vimrc dir_colors)
 for dotfile in "${DOTFILES_SAFE[@]}"; do
   safe_copy "$dotfile"
 done
 
+# Disable welcome on .screenrc
+if [ -f ~/.screenrc ]; then
+  grep -q startup_message ~/.screenrc || echo "startup_message off" >>~/.screenrc
+else
+  echo "startup_message off" >>~/.screenrc
+fi
+
 # Copy GIT_ variable values to .gitconfig
 if [[ "$(uname)" =~ Darwin ]]; then
-  [ -f "$HOME/.bash_profile" ] && . "$HOME/.bash_profile"
+  [ -f ~/.bash_profile ] && . ~/.bash_profile
   [ "$GIT_AUTHOR_NAME" ]  && git config --global user.name  "$GIT_AUTHOR_NAME"
   [ "$GIT_AUTHOR_EMAIL" ] && git config --global user.email "$GIT_AUTHOR_EMAIL"
 fi
 
 # Check if .bash_profile has no values
-[ -f "$HOME/.bash_apikeys" ] && rm -f "$HOME/.bash_apikeys"
-if [ -f "$HOME/.bash_profile" ]; then
-  unset HOMEBREW_GITHUB_API_TOKEN GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL 
-  unset GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL 
-  . "$HOME/.bash_profile"
+[ -f ~/.bash_apikeys ] && rm -f /.bash_apikeys
+if [ -f ~/.bash_profile ]; then
+  unset HOMEBREW_GITHUB_API_TOKEN GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL
+  unset GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL
+  . ~/.bash_profile
   if [ ! "$HOMEBREW_GITHUB_API_TOKEN" ] && [ ! "$GIT_AUTHOR_NAME" ] && \
      [ ! "$GIT_AUTHOR_EMAIL" ] && [ ! "$GIT_COMMITTER_NAME" ] && \
      [ ! "$GIT_COMMITTER_EMAIL" ]; then
@@ -51,8 +58,8 @@ fi
 
 # Disable GIT_ env from profile on Linux/BSD
 if [[ ! "$(uname)" =~ Darwin ]]; then
-  sed -i 'bak' -e 's/^export GIT/#export GIT/g' "$HOME/.bash_profile"
-  rm -f "$HOME/.bash_profile.bak"
+  sed -i 'bak' -e 's/^export GIT/#export GIT/g' ~/.bash_profile
+  rm -f ~/.bash_profile.bak
 fi
 
 # Remove push.default=simple for old git versions
@@ -65,8 +72,5 @@ if hash git >/dev/null 2>&1; then
 fi
 
 # All done
-echo
-echo "New dotfiles on $HOME/.dotfiles"
-echo "Backup of your last dotfiles on $HOME/.dotfiles_backup"
-echo
-echo "All done. Restart your terminal"
+unset __DF_BASHRC __DF_BASH_COMMON __DF_PROFILE
+. ~/.bashrc
